@startuml

title __INTERFACE_API's Class Diagram__\n

  namespace com.example.finalproject {
    namespace interface_api {
      interface com.example.finalproject.interface_api.Admin_item_interface {
          {abstract} + itemlist()
      }
    }
  }
  

  namespace com.example.finalproject {
    namespace interface_api {
      class com.example.finalproject.interface_api.ApiClient {
          {static} - retrofit : Retrofit
          {static} + getClient()
      }
    }
  }
  

  namespace com.example.finalproject {
    namespace interface_api {
      interface com.example.finalproject.interface_api.ApiInterface {
          {abstract} + forgot_password()
          {abstract} + insert_items()
          {abstract} + issued_item_list()
          {abstract} + items_list()
          {abstract} + loginUser()
          {abstract} + logout()
          {abstract} + registerUser()
          {abstract} + return_issued_item()
          {abstract} + update_del_items()
          {abstract} + user_item_issued()
      }
    }
  }
  

  namespace com.example.finalproject {
    namespace interface_api {
      class com.example.finalproject.interface_api.CSPreferences {
          {static} + clearPref()
          {static} + getBoolean()
          {static} + getString()
          {static} + putBolean()
          {static} + putString()
          {static} + readString()
          {static} - getPreferences()
      }
    }
  }
  

  namespace com.example.finalproject {
    namespace interface_api {
      interface com.example.finalproject.interface_api.Issued_item_list_interface {
          {abstract} + Issued_item_list()
      }
    }
  }
  

  namespace com.example.finalproject {
    namespace interface_api {
      class com.example.finalproject.interface_api.WebApicall {
          ~ pd : ProgressDialog
          + dailoghide()
          + dailogshow()
          + forgot_password()
          + insert_items()
          + issued_item_list()
          + items_list()
          + return_issued_item()
          + update_del_items()
          + user_item_issued()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
